import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import Container from '../components/Container'
import { useStore } from '../hooks/useStore'

const CartPage = () => {
  const { cart, itemCount, subtotal, updateQuantity, removeFromCart } = useStore()
  const shipping = subtotal >= 100 || subtotal === 0 ? 0 : 12
  const total = subtotal + shipping

  if (!cart.length) return <div className="min-h-screen bg-ivory text-forest"><main className="pt-36 pb-28 sm:pt-44"><Container><div className="mx-auto max-w-xl text-center"><ShoppingBag size={24} strokeWidth={1} className="mx-auto text-gold" /><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.28em] text-gold">Your garden bag</p><h1 className="mt-5 font-display text-6xl leading-none">A quiet space, for now.</h1><p className="mx-auto mt-6 max-w-sm text-sm leading-7 text-forest/60">Your cart is waiting for the first piece of your indoor garden.</p><Link to="/shop" className="mt-9 inline-flex items-center gap-3 rounded-full bg-forest px-6 py-3.5 text-sm font-semibold text-ivory transition hover:-translate-y-0.5 hover:bg-fern">Explore plants</Link></div></Container></main></div>

  return <main className="min-h-screen bg-ivory pb-28 pt-32 text-forest sm:pt-40"><Container><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-gold">Your garden bag</p><h1 className="mt-4 font-display text-6xl leading-none">Ready to take root.</h1></div><p className="text-sm text-forest/55">{itemCount} {itemCount === 1 ? 'plant' : 'plants'}</p></div><div className="mt-14 grid gap-12 lg:grid-cols-[1fr_0.38fr]"><section className="divide-y divide-forest/10 border-y border-forest/10">{cart.map((item) => <div key={item.id} className="flex gap-5 py-6"><img src={`https://images.unsplash.com/${item.image}?auto=format&fit=crop&w=300&q=85`} alt={item.name} className="size-28 rounded-xl object-cover sm:size-36" /><div className="flex min-w-0 flex-1 flex-col justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-gold">{item.category}</p><Link to={`/product/${item.id}`} className="mt-1 block font-display text-2xl hover:text-fern">{item.name}</Link><p className="mt-1 text-sm text-forest/55">${item.price}</p></div><div className="flex items-center justify-between gap-4"><div className="flex items-center rounded-full border border-forest/15"><button aria-label={`Decrease ${item.name}`} onClick={() => updateQuantity(item.id, item.quantity - 1)} className="grid size-8 place-items-center"><Minus size={13} /></button><span className="w-7 text-center text-xs">{item.quantity}</span><button aria-label={`Increase ${item.name}`} onClick={() => updateQuantity(item.id, item.quantity + 1)} className="grid size-8 place-items-center"><Plus size={13} /></button></div><button onClick={() => removeFromCart(item.id)} aria-label={`Remove ${item.name}`} className="text-forest/40 hover:text-red-800"><Trash2 size={16} /></button></div></div></div>)}</section><aside className="h-fit rounded-2xl bg-sage/60 p-7"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-gold">Order summary</p><div className="mt-8 space-y-4 text-sm"><div className="flex justify-between"><span className="text-forest/55">Subtotal</span><span>${subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span className="text-forest/55">Plant care delivery</span><span>{shipping ? `$${shipping.toFixed(2)}` : 'Free'}</span></div><div className="border-t border-forest/15 pt-4 text-base font-semibold flex justify-between"><span>Total</span><span>${total.toFixed(2)}</span></div></div><button className="mt-8 w-full rounded-full bg-forest px-5 py-4 text-sm font-semibold text-ivory transition hover:bg-fern">Continue to checkout</button><Link to="/shop" className="mt-6 flex items-center justify-center gap-2 text-xs font-semibold text-forest/55 hover:text-fern"><ArrowLeft size={13} /> Continue shopping</Link></aside></div></Container></main>
}

export default CartPage
