import { ArrowRight, ArrowUpRight, Leaf, Mail, MapPin, Phone, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import Container from '../components/Container'
import SectionTitle from '../components/SectionTitle'
import { products } from '../data/products'
import QuickView from '../components/QuickView'

const pageContent = {
  shop: { eyebrow: 'The first edit', title: 'Living pieces for considered spaces.', intro: 'A small, thoughtful collection of botanicals chosen for their character, resilience, and quiet ability to change a room.' },
  collections: { eyebrow: 'Find your rhythm', title: 'Collections with a pulse.', intro: 'Explore future edits shaped around light, mood, and the way you make a home your own.' },
  about: { eyebrow: 'The Eden Flora way', title: 'A little more life, in every room.', intro: 'Eden Flora is a slower kind of plant company, built around thoughtful growing, honest guidance, and the restorative power of nature at home.' },
  contact: { eyebrow: 'Come say hello', title: 'Let’s grow something beautiful.', intro: 'Questions about a plant, your space, or the collection ahead? Our greenhouse door is always open.' },
}

const collections = [
  ['Low light', 'For the quiet corners', 'photo-1509423350716-97f9360b4e09'],
  ['Statement plants', 'For a little drama', 'photo-1614594975525-e45190c55d0b'],
  ['Small rituals', 'For desks and shelves', 'photo-1485955900006-10f4d324d411'],
]

const SitePage = ({ type }) => {
  const content = pageContent[type]
  return <div className="min-h-screen bg-ivory text-forest"><main className="pb-24 pt-32 sm:pb-32 sm:pt-40"><Container>{type === 'shop' ? <ShopHero content={content} /> : type === 'collections' ? <CollectionsHero content={content} /> : <IntroHero content={content} type={type} />}{type === 'contact' ? <ContactDetails /> : type === 'about' ? <AboutDetails /> : null}</Container></main></div>
}

const IntroHero = ({ content, type }) => <div className="grid gap-16 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><SectionTitle eyebrow={content.eyebrow} title={content.title} description={content.intro} /><div className="relative overflow-hidden rounded-[1rem_8rem_1rem_8rem] bg-sage p-3 shadow-[18px_28px_55px_rgba(27,58,42,0.1)]"><div className="aspect-[1.45] overflow-hidden rounded-[0.75rem_7.5rem_0.75rem_7.5rem]"><img src={type === 'about' ? 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1400&q=85' : 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?auto=format&fit=crop&w=1400&q=85'} alt={type === 'about' ? 'Botanical interior with plants and natural light' : 'Eden Flora greenhouse interior'} className="h-full w-full object-cover transition-transform duration-700 hover:scale-105" /></div></div></div>

const ShopHero = ({ content }) => {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All plants')
  const filtered = useMemo(() => products.filter((product) => (filter === 'All plants' || product.category.toLowerCase().includes(filter.toLowerCase())) && product.name.toLowerCase().includes(query.toLowerCase())), [filter, query])
  const [selectedProduct, setSelectedProduct] = useState(null)
  return <><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><SectionTitle eyebrow={content.eyebrow} title={content.title} description={content.intro} /><div className="rounded-[1rem_8rem_1rem_8rem] bg-forest p-8 text-ivory sm:p-12"><p className="text-[10px] font-bold uppercase tracking-[0.26em] text-gold">The greenhouse edit / 2026</p><p className="mt-8 max-w-sm font-display text-4xl leading-none sm:text-5xl">Bring a little more life home.</p><Link to="/collections" className="mt-8 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[0.18em] text-ivory/75 hover:text-gold">Browse by room <ArrowRight size={15} /></Link></div></div><div className="mt-20 flex flex-wrap items-center justify-between gap-5 border-y border-forest/10 py-5"><div className="flex flex-wrap items-center gap-5 text-xs font-semibold text-forest/60"><button onClick={() => setFilter('All plants')} className={filter === 'All plants' ? 'text-forest' : ''}>All plants</button><button onClick={() => setFilter('Low light')} className={filter === 'Low light' ? 'text-forest' : ''}>Low light</button><button onClick={() => setFilter('Statement')} className={filter === 'Statement' ? 'text-forest' : ''}>Statement</button><button onClick={() => setFilter('Small rituals')} className={filter === 'Small rituals' ? 'text-forest' : ''}>Small rituals</button><button onClick={() => setFilter('Tropical')} className={filter === 'Tropical' ? 'text-forest' : ''}>Tropical</button></div><label className="flex items-center gap-2 border-b border-forest/15 pb-2 text-xs text-forest/60"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search plants" className="w-28 bg-transparent outline-none placeholder:text-forest/40" /></label></div><p className="mt-6 text-xs text-forest/45">Showing {filtered.length} of {products.length} plants</p><section className="mt-8 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((product) => <ProductCard key={product.id} product={product} onQuickView={setSelectedProduct} />)}</section>{selectedProduct && <QuickView product={selectedProduct} onClose={() => setSelectedProduct(null)} />}</>
}

const ProductCard = ({ product, onQuickView }) => <motion.div layout className="group"><button type="button" onClick={() => onQuickView(product)} data-cursor-label="View" className="relative block w-full aspect-[0.86] overflow-hidden rounded-2xl bg-sage text-left"><img loading="lazy" src={`https://images.unsplash.com/${product.image}?auto=format&fit=crop&w=800&q=85`} alt={`View ${product.name}`} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-ivory/85 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[0.14em] text-forest">New growth</span><span className="absolute bottom-4 right-4 grid size-10 place-items-center rounded-full bg-ivory text-forest opacity-0 shadow-lg transition group-hover:opacity-100"><ArrowUpRight size={16} /></span></button><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.18em] text-gold">{product.category}</p><div className="mt-1 flex justify-between gap-3"><Link to={`/product/${product.id}`} className="font-display text-2xl text-forest hover:text-fern">{product.name}</Link><span className="pt-1 text-sm font-semibold text-fern">${product.price}</span></div></motion.div>

const CollectionsHero = ({ content }) => <><div className="max-w-2xl"><SectionTitle eyebrow={content.eyebrow} title={content.title} description={content.intro} /></div><section className="mt-16 grid gap-4 md:grid-cols-3">{collections.map(([name, subtitle, image], index) => <Link to="/shop" key={name} className={`group relative overflow-hidden rounded-[1rem_5rem_1rem_5rem] bg-sage ${index === 1 ? 'md:mt-16' : ''}`}><div className="aspect-[0.78]"><img src={`https://images.unsplash.com/${image}?auto=format&fit=crop&w=900&q=85`} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="absolute inset-0 bg-linear-to-t from-forest/80 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 text-ivory"><p className="text-[9px] font-bold uppercase tracking-[0.22em] text-gold">0{index + 1}</p><h2 className="mt-2 font-display text-3xl">{name}</h2><p className="mt-1 text-xs text-ivory/70">{subtitle}</p></div></Link>)}</section></>

const AboutDetails = () => <section className="mt-24 grid gap-12 border-t border-forest/10 pt-12 md:grid-cols-2 sm:mt-32 sm:pt-16"><div><Leaf size={22} strokeWidth={1} className="text-gold" /><h2 className="mt-6 font-display text-4xl">Plants are not decoration. They are presence.</h2></div><p className="max-w-md text-sm leading-8 text-forest/65">We work with growers who understand that every plant has a point of view. Our role is to help it find the right room, the right light, and the right person. The result is a home that feels less furnished, and more alive.</p></section>

const ContactDetails = () => <section className="mt-24 grid gap-4 border-t border-forest/10 pt-12 sm:grid-cols-3 sm:pt-16"><a href="mailto:hello@edenflora.co" className="rounded-2xl bg-sage/55 p-7 transition hover:bg-sage"><Mail size={18} className="text-gold" /><p className="mt-8 text-sm font-semibold">hello@edenflora.co</p><p className="mt-1 text-xs text-forest/50">Write to the greenhouse</p></a><a href="tel:+18003363372" className="rounded-2xl bg-sage/55 p-7 transition hover:bg-sage"><Phone size={18} className="text-gold" /><p className="mt-8 text-sm font-semibold">+1 800 336 3372</p><p className="mt-1 text-xs text-forest/50">Monday to Friday</p></a><div className="rounded-2xl bg-sage/55 p-7"><MapPin size={18} className="text-gold" /><p className="mt-8 text-sm font-semibold">The Eden greenhouse</p><p className="mt-1 text-xs text-forest/50">Brooklyn, New York</p></div></section>

export default SitePage
