import { ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import Container from '../components/Container'
import SectionTitle from '../components/SectionTitle'
import { getProductImage, products } from '../data/products'

const FeaturedPlants = () => <section id="shop" className="bg-ivory py-24 sm:py-32"><Container><div className="flex flex-wrap items-end justify-between gap-6"><SectionTitle eyebrow="The first edit" title="Living well starts here." description="A considered collection of beautiful, living things, chosen to bring calm into the everyday." /><Link to="/shop" data-cursor-label="View" className="group mb-1 inline-flex items-center gap-3 border-b border-fern/40 pb-2 text-sm font-semibold text-fern">View all plants <ArrowUpRight size={16} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map((product) => <div key={product.id} className="group"><Link to={`/product/${product.id}`} data-cursor-label="View" className="block"><div className="aspect-[0.9] overflow-hidden rounded-2xl bg-sage"><img loading="eager" src={getProductImage(product, 800)} alt={product.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.18em] text-gold">{product.category}</p><div className="mt-1 flex justify-between gap-3"><h3 className="font-display text-2xl text-forest">{product.name}</h3><span className="pt-1 text-sm text-fern">${product.price}</span></div></Link><Link to={`/passport/${product.id}`} data-cursor-label="Passport" className="mt-4 inline-flex items-center gap-2 rounded-full border border-forest/15 px-4 py-2 text-[9px] font-bold uppercase tracking-[0.16em] text-fern transition hover:-translate-y-0.5 hover:border-gold hover:bg-sage">View Passport <ArrowUpRight size={13} /></Link></div>)}</div></Container></section>

export default FeaturedPlants
