import { ArrowUpRight, BookOpen } from 'lucide-react'
import { motion } from 'framer-motion'
import Container from '../components/Container'
import SectionTitle from '../components/SectionTitle'
import { journalStories } from '../data/editorial'

const GardenJournal = () => <section className="bg-ivory py-24 sm:py-32"><Container><div className="flex flex-wrap items-end justify-between gap-6"><SectionTitle eyebrow="From the greenhouse" title="Notes for a more considered life." description="Growing guides, room stories, and small reminders to make space for what restores you." /><span className="mb-1 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-forest/45"><BookOpen size={15} className="text-gold" /> Eden journal</span></div><div className="mt-14 grid gap-8 md:grid-cols-3">{journalStories.map((story, index) => <motion.article key={story.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.7, delay: index * 0.12 }} className="group"><div className="relative aspect-[1.08] overflow-hidden rounded-[1rem_4rem_1rem_4rem] bg-sage"><img src={story.image} alt={story.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="pointer-events-none absolute inset-0 bg-linear-to-t from-forest/20 via-transparent to-sage/10" /><span className="absolute left-5 top-5 grid size-9 place-items-center rounded-full bg-ivory/85 text-forest"><span className="font-display text-lg">0{index + 1}</span></span></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[0.2em] text-gold">{story.eyebrow}</p><h3 className="mt-2 max-w-xs font-display text-3xl leading-none text-forest">{story.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-forest/55">{story.summary}</p><button className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-fern">Read the note <ArrowUpRight size={14} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></button></motion.article>)}</div></Container></section>

export default GardenJournal
